services:
  metadata_frontend:
    build: ./../.
    container_name: ztistudio
    environment:
      - PORT=3009
      - HOST=0.0.0.0
    env_file:
      - ./.env
    networks:
      - nginx_network
    restart: always

networks:
  nginx_network:
    external: true
