name: push_cd

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker -f compose docker/docker-compose-prod.yml up -d --build
